# ESP32-S3-Touch-LCD-7
substitutions:
  name: "your-device-name"
  friendly_name: "Your Room Sensor"
  room: "Your Room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup: github://AlexanderRubbel/esphome-lvgl/guition-esp32-s3-4848s040/package.yaml@98d35ad37b3ec9aba75af6a613d19c4f2e1a841a
